module.exports = {
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "private",
  "BOT_NUMBER": "94741541440",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": true,
  "AUTO_STICKER": true,
  "AUTO_REPLY": false,
  "AUTO_REACT": false,
  "WELCOME": false,
  "MNAME": "PODIYA XPRO",
  "ANTI_BAD": [],
  "ANTI_BOT": [],
  "ANTI_LINK": [],
  "ANTI_CALL": false,
  "ANTI_DELETE": false,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": "3",
  "OWNER_NAME": "MR PEKSHA",
  "NEWS_JID": false,
  "MOVIE_JID": [
    "94741541440@s.whatsapp.net"
  ],
  "ANIME_JID": false,
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false,
  "FOOTER": "> QUEEN ANJU XPRO\n> Developed by Mr. Rashmika\n> GitHub Repository: github.com/Mrrashmika/QUEEN_ANJU_xPro\n🌟 Premium Version | Advanced Features | Secure & Reliable 🌟\n© 2025 QUEEN ANJU XPRO. All rights reserved.",
  "OWNER_REACT": false,
  "EMOJI": "🏷",
  "AI_MODE": false,
  "AI": "RASH",
  "BANNED": [],
  "SUDO": [
    "94741541440"
  ],
  "LANG": "EN",
  "MAX_SIZE": 100,
  "ONLY_GROUP": false,
  "ALIVE": "default",
  "LOGO": "https://i.ibb.co/5g5frmz9/thisjpg.jpg"
};
